name: Validate latest release

on:
  push:
    branches:
      - main
    paths:
      - 'releases/**'
      - '.github/workflows/validate_latest.yml'
  pull_request:
    branches:
      - main
    paths:
      - 'releases/**'
      - '.github/workflows/validate_latest.yml'


jobs:
  validate-latest-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Identify highest version releases directory
        id: find-version
        run: |
          latest_version=$(ls releases/ | grep -E '^[0-9]{4}-[0-9]{2}-[0-9]{2}$' | sort | tail -n1)
          echo "latest_version=$latest_version" >> "$GITHUB_OUTPUT"
          echo "Latest version directory: $latest_version"

      - name: Compare latest to highest version
        run: |
          diff_output=$(diff -r releases/latest releases/${{ steps.find-version.outputs.latest_version }}) || (echo "$diff_output"; exit 1)
          echo "✅ 'latest' releases matches highest version: ${{ steps.find-version.outputs.latest_version }}"
